alpdesk_frontendediting:
  path: /%contao.backend.route_prefix%/alpdeskfee
  defaults:
    _controller: Alpdesk\AlpdeskFrontendediting\Controller\BackendController:endpoint
    _scope: backend
    _token_check: false
  methods: [ POST ]

alpdesk_frontendediting_backend:
  path: /%contao.backend.route_prefix%/alpdeskfeebackend
  defaults:
    _controller: Alpdesk\AlpdeskFrontendediting\Controller\AlpdeskbackendController:endpoint
    _scope: backend
  methods: [ POST, GET ]
